version: '3.3'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
    ports:
      - "8087:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_PASSWORD=er0swccd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=week8TR1